- hosts: all
  become: true

  vars:
    ansible_python_interpreter: '/usr/local/bin/python3.6'
    host_ioc_release_version: '11.3-RELEASE'

  tasks:
    - import_role:
        name: 'JoergFiedler.freebsd-jail-host'
    - include_role:
        name: 'JoergFiedler.freebsd-jailed-rslsync'
      vars:
        jail_net_ip: '10.1.0.10'
        jail_name: 'rslsync'
        jail_freebsd_release: '{{ host_ioc_release_version }}'
        jail_build_server_enabled: yes
        jail_build_server_url: 'http://vastland.moumantai.de/public/FreeBSD/packages/freebsd-11_3_x64-branches_2019Q4'
