- hosts: all
  become: true

  tasks:
    - import_role:
        name: 'JoergFiedler.freebsd-jail-host'
    - include_role:
        name: 'JoergFiedler.freebsd-jailed-rslsync'
      vars:
        jail_net_ip: '10.1.0.10'
        jail_name: 'rslsync'
        jail_build_server_enabled: yes
        jail_build_server_url: 'http://vastland.moumantai.de/public/FreeBSD/packages/freebsd-12_1_x64-branches_2019Q4'
