---
- name: Create rslsync s ZFS dataset s mount point
  file:
    path: '{{ rslsync_home_host_zfs_dir }}'
    state: directory

- name: Create rslsync ZFS dataset
  zfs:
    name: '{{ host_zfs_rslsync_dataset }}'
    state: present
    extra_zfs_properties:
      atime: 'off'
      mountpoint: '{{ host_zfs_rslsync_dir }}'

- name: Create rslsync instance s ZFS dataset
  zfs:
    name: '{{ rslsync_home_host_zfs_dataset }}'
    state: present
    extra_zfs_properties:
      atime: 'off'
      mountpoint: '{{ rslsync_home_host_zfs_dir }}'

- name: Create rslsync instance's mountpoint
  file:
    path: '{{ jail_home.stdout }}{{ rslsync_home }}'
    state: directory

- name: Configure jail to mount file system from host
  mount:
    name: '{{ jail_home.stdout }}{{ rslsync_home }}'
    fstab: '{{ jail_home.stdout }}/../fstab'
    fstype: 'nullfs'
    opts: 'rw'
    src: '{{ rslsync_home_host_zfs_dir }}'
    state: present
